-- brand_assets_us.sql — generated by scripts/seed-brand-assets.js
-- REAL, origin-validated US product imagery. Do not hand-edit; re-run the seeder.
insert into public.brand_assets (sku_key, asset_type, url, alt, width, height, source_pdp, origin_validated, status, region) values
  ('logo', 'logo', 'https://www.vahdam.com/cdn/shop/files/logo-website_3.png?v=1754032931', 'VAHDAM logo (US)', 1000, null, 'https://www.vahdam.com', true, 'verified', 'us'),
  ('masala_chai_100ct', 'product', 'https://www.vahdam.com/cdn/shop/files/100_TB-31_4fb347b1-a1d5-4b72-93f8-0bc9a112e688.jpg', 'India''s Original Masala Chai Tea, 100 Count', 1000, 1000, 'https://www.vahdam.com/products/indias-original-masala-chai-tea-100-tea-bags', true, 'verified', 'us'),
  ('masala_chai_12oz', 'product', 'https://www.vahdam.com/cdn/shop/files/Original_chai_ba5f65d4-7560-4423-b25a-c09cd33e7172.jpg', 'India''s Original Masala Chai Tea, 12 oz', 1000, 1000, 'https://www.vahdam.com/products/indias-original-masala-chai-tea-loose-leaf-12oz', true, 'verified', 'us'),
  ('masala_chai_30ct', 'product', 'https://www.vahdam.com/cdn/shop/files/2_57439e6a-108d-4ed8-b07c-ff8afc96663d.jpg', 'India''s Original Masala Chai Tea, 30 Count', 1000, 1000, 'https://www.vahdam.com/products/indias-original-masala-chai-tea-30-tea-bags', true, 'verified', 'us'),
  ('double_spice_353oz', 'product', 'placeholder:double_spice_353oz:product', 'double_spice_353oz: no verified US handle', null, null, null, false, 'placeholder', 'us'),
  ('turmeric_ginger_100ct', 'product', 'https://www.vahdam.com/cdn/shop/files/Organic_Turmeric_Ginger_Front.jpg', 'Turmeric Ginger Herbal Tea Tisane, 100 Count', 1000, 1000, 'https://www.vahdam.com/products/turmeric-ginger-herbal-tea-100-tea-bags', true, 'verified', 'us'),
  ('daily_assam_12oz', 'product', 'https://www.vahdam.com/cdn/shop/files/Daily-Assam.jpg', 'Daily Assam Black Tea, 12 oz', 1000, 1000, 'https://www.vahdam.com/products/daily-assam-black-tea-12oz', true, 'verified', 'us'),
  ('himalayan_green_12oz', 'product', 'https://www.vahdam.com/cdn/shop/files/Himalayan_green_tea_f953d287-3e7a-4973-9957-5e6e8bd22130.jpg', 'Himalayan Green Tea, 12 oz', 1000, 1000, 'https://www.vahdam.com/products/himalayan-green-tea-loose-leaf-12oz', true, 'verified', 'us'),
  ('english_breakfast_12oz', 'product', 'https://www.vahdam.com/cdn/shop/files/English_Breakfast.jpg', 'English Breakfast Black Tea, 12 oz', 1000, 1000, 'https://www.vahdam.com/products/classic-english-breakfast-black-loose-leaf-tea-12oz', true, 'verified', 'us'),
  ('daily_darjeeling_2f_12oz', 'product', 'https://www.vahdam.com/cdn/shop/files/Copy_of_castleton-half_11zon_d5872785-939e-486e-9018-feca5a2c94ca.jpg', '2025 Castleton Classic Darjeeling Second Flush Black Tea DJ 354', 1000, 1000, 'https://www.vahdam.com/products/castleton-classic-darjeeling-second-flush-black-tea-dj-354', true, 'verified', 'us'),
  ('assorted_sampler_10', 'product', 'https://www.vahdam.com/cdn/shop/files/Assorted-Samler-20-Varinats_front.png', 'Assorted Tea Bags Sampler, (40 Pyramid Tea Bags) 20 Flavors', 1000, 1000, 'https://www.vahdam.com/products/assorted-tea-bags-sampler-2-x-20-variants', true, 'verified', 'us')
on conflict (sku_key, asset_type, url) do update set
  alt = excluded.alt, width = excluded.width, height = excluded.height,
  source_pdp = excluded.source_pdp, origin_validated = excluded.origin_validated,
  status = excluded.status, region = excluded.region;
